######################################################################
# Automatically generated by qmake (2.00a) sam. 7. janv. 18:07:14 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h Menu.h OgreView.h
SOURCES += main.cpp MainWindow.cpp Menu.cpp OgreView.cpp
